services:
  - type: web
    name: ng-portfolio
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist/ng-portfolio
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 